#!/usr/bin/env bash
# install files in the home of user "Pi"
cd /home/pi
# install packages
apt-get install git bc i2c-tools python python-imaging -y
# install pip
echo -e "Installing pip";
curl --silent --show-error --retry 5 https://bootstrap.pypa.io/get-pip.py | python2.7
# install paho mqtt
echo -e "Installing paho-mqtt";
pip install paho-mqtt
wget -q https://goo.gl/dr5I7u -O /home/pi/papirus-mqtt.py && chmod +x /home/pi/papirus-mqtt.py
git clone https://github.com/PiSupply/PaPiRus.git
cd PaPiRus
python setup.py install    # Install PaPirRus python library
papirus-setup    # Install drivers and setup epaper
